### ISSUE TITLE
Possible to upgrade to SDL >= 2.0.7?

### ISSUE THREAD

**Issue by petmac** [lasote/conan-sdl2#16]
Our project uses [SDL_AudioStream](https://wiki.libsdl.org/SDL_AudioStream), which arrived in 2.0.7.

**Comment by Croydon** [comment]
I'm not sure if lasote will maintain this further. You could check out https://github.com/bincrafters/conan-sdl2

**Comment by petmac** [comment]
Oh! Thank you. I wasn't aware of that repo.
